### ISSUE TITLE
Documentation for Rate limiting on ECR

### ISSUE THREAD

**Issue by Tibingeo** [awsdocs/amazon-ecr-user-guide#11]
Recently we are facing rate-limiting issues on ECR, error is toomanyrequests: Rate exceeded, 
We have a docker image with ~40 layer when we do a docker push  some time total api transactions will be 40-15 but some time it will be 100-150 transactions. 
Why this scenario occurs as image layer nothing is changed but api transactions like `InitiateLayerUpload` differs in huge amount.

There is no proper error where it's says on which api call it is failing.

**Comment by karisNg** [comment]
We have threaded some simple docker push and recently started getting these rate-limiting issues too. 
A section about how "# of docker transaction" is calculated so we can throttle accordingly would be great too.

**Comment by joelbrandenburg** [comment]
We have documentation for the Amazon ECR service limits, including what the API limits are.  You can view those here: https://docs.aws.amazon.com/AmazonECR/latest/userguide/service_limits.html

Let me know if that helps or if further information is needed.
