### ISSUE TITLE
Not able delete ECR repository by any IAM user

### ISSUE THREAD

**Issue by sam0104** [awsdocs/amazon-ecr-user-guide#13]
Please provide information how to delete a repository with DENY to all IAM users 

I was playing with ECR repository and created a test repository and by mistake applied DENY all access to all IAM users. Now I am not able to delete this repository. Is there a way to delete this repository ?

$ *aws ecr delete-repository --repository-name test*

An error occurred (AccessDeniedException) when calling the DeleteRepository operation: User: arn:aws:iam::421414164445:user/user1 is not authorized to perform: ecr:DeleteRepository on resource: arn:aws:ecr:us-east-2:421414164445:repository/test with *an explicit deny*

Thanks 
Sas

**Comment by joelbrandenburg** [comment]
@sam0104 I see you also opened up a documentation feedback ticket and we'll work through this with you through that ticket.  Thanks.
