### ISSUE TITLE
Documenting repository S3 buckets

### ISSUE THREAD

**Issue by jsha09** [awsdocs/amazon-ecr-user-guide#24]
It would very handy to have documentation here (maybe Repositories.md) describing that:
- Image manifests come from the  *dkr.ecr.ap-southeast-2.amazonaws.com endpoint
- Image layers are coming from the prod-<REGION>-starport-layer-bucket.s3.us-east-1.amazonaws.com S3 buckets

**Comment by joelbrandenburg** [comment]
This is an older issue, but this information is documented here:
https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html
