### ISSUE TITLE
OCI Artifact page improvements

### ISSUE THREAD

**Issue by rikatz** [awsdocs/amazon-ecr-user-guide#32]
Couldn't find the markdown of the OCI Artifact pages, so opening an issue here:

* Step 5.b should be:

```
helm create mychart
rm -rf ./mychart/templates/*
```
(It either needs a leading . before the /mychart, or turn /mychart into mychart/templates/*)

* Step 2 or 3 - Create some environment variables to be used later in the registry creation and pushing:

```
export REGION=$(aws configure get region)
export ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)
```

* After exporting the variables above, step 4 (and all that references either REGION and/or ACCOUNT) can be replaced as the following:

```
aws ecr get-login-password \
     --region ${REGION} | helm registry login \
     --username AWS \
     --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
```

and 
```
helm chart save . ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/artifact-test:mychart
```
(there are other parts in the text that can be replaced)

**Comment by rikatz** [comment]
cc @joelbrandenburg

**Comment by joelbrandenburg** [comment]
The repository has been updated to include the latest changes to the Amazon ECR User Guide.  I've fixed the typo you describe in step 5.b.  I also realize that using environment variables is helpful but we generally don't use that style in the documentation so I left that out.
