### ISSUE TITLE
Chart versions as tags

### ISSUE THREAD

**Issue by luisdavim** [awsdocs/amazon-ecr-user-guide#39]
from reading https://helm.sh/docs/topics/registries/ I got the idea the pattern to use would be something like:

```
helm chart save . mychart
helm chart save . aws_account_id.dkr.ecr.us-west-2.amazonaws.com/artifact-test/mychart
helm chart push aws_account_id.dkr.ecr.region.amazonaws.com/artifact-test/mychart:v0.1.0
```

but that fails and 

```
helm chart save . mychart:v0.1.0
helm chart save . aws_account_id.dkr.ecr.us-west-2.amazonaws.com/artifact-test/mychart:v0.1.0
helm chart push aws_account_id.dkr.ecr.region.amazonaws.com/artifact-test/mychart:v0.1.0
```

also fails so how are we supposed to specify the version? Are we supposed to create a repository per chart and use:

```
helm chart save . mychart
helm chart save . aws_account_id.dkr.ecr.us-west-2.amazonaws.com/mychart
helm chart push aws_account_id.dkr.ecr.region.amazonaws.com/mychart:v0.1.0
```

I think this should be clarified in the documentation.

**Comment by joelbrandenburg** [comment]
With the release of Helm 3.7.0, I think this process becomes easier.  Take a look at the updated documentation for working with Helm charts in the ECR guide and reopen this request if it isn't more clear.
