### ISSUE TITLE
Help Wanted – Troubleshooting, Tips, and Tricks

### ISSUE THREAD

**Issue by joelbrandenburg** [awsdocs/amazon-ecr-user-guide#4]
Please share your experience! If you've hit a problem and solved it, I’d love to hear from you. I am also interested in any tips or tricks you’ve learned along the way.

Submit a pull request (instructions [here](https://github.com/awsdocs/amazon-ecr-user-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the Amazon ECR User Guide.

Thank you for your time. I look forward to hearing from you!

**Comment by cheungtom** [comment]
@joelbrandenburg:
Hello, my name is Tom and I work for AWS (my email: cheungto@amazon.com). To upgrade ECS Fargate Service from platform v1.3 to v.1.4, there is one additional ECR VPC endpoint need "com.amazonaws.region.ecr.api" if the VPC with no Internet access and ECS Fargate need to pull Image from ECR. I want to suggest below vpc endpoint policy for such ECR API vpc endpoint at file "vpc-endpoints.md". This may help some customer who need strict vpc endpoint policy other than full permission or some wildcard rule.

The following endpoint policy example is for **com\.amazonaws\.*region*\.ecr\.api **\. The 1st policy is specific for ECR actions for resource type of ECR repository\. For this example, it is for all respositories under the specfic AWS account within a region\. The 2nd policy is specific for ECR actions not target for resource type of ECR repository. Therefore, we need to use wildcard for the resources attribute.
```
{
    "Statement": [
        {
            "Sid": "AllowAllRepoType",
            "Principal": {
               "AWS": "arn:aws:iam::1234567890:role/ecsTaskExecutionRole"
            },
            "Action": [
                "ecr:*"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:ecr:region:1234567890:repository/*"
        },
        {
            "Sid": "AllowAllNonRepoType",
            "Principal": {
               "AWS": "arn:aws:iam::1234567890:role/ecsTaskExecutionRole"
            },
            "Action": [
                "ecr:DeleteRegistryPolicy",
                "ecr:DescribeRegistry",
                "ecr:GetAuthorizationToken",
                "ecr:GetRegistryPolicy",
                "ecr:PutRegistryPolicy",
                "ecr:PutReplicationConfiguration"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

Thanks much! Feel free to contact me by amazon email if need. Thanks!

Best regards!
Tom

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
