### ISSUE TITLE
Not the same content on website vs github

### ISSUE THREAD

**Issue by PaulinCharliquart** [awsdocs/amazon-ecr-user-guide#43]
hi,
There is an issue in the examples published on step 6 and 7 ([docs](https://docs.aws.amazon.com/AmazonECR/latest/userguide/getting-started-cli.html#cli-delete-repository)).
I tried to fix it on this repo but there is no mention of the region parameter in the [source doc](https://github.com/awsdocs/amazon-ecr-user-guide/blob/main/doc_source/getting-started-cli.md#step-6-delete-an-image).

```
# add missing \ after force
aws ecr delete-repository \
      --repository-name hello-world \
      --force \
      --region region
```

KR,
Paulin

**Comment by joelbrandenburg** [comment]
We appreciate you pointing out this typo, we have made an update to the documentation to fix this.
