### ISSUE TITLE
Help Wanted - Lifecycle Policy Examples

### ISSUE THREAD

**Issue by joelbrandenburg** [awsdocs/amazon-ecr-user-guide#5]
Please share your example lifecycle policies! If you have a useful or interesting lifecycle policy example that you feel other users could benefit from, let us know.

Submit a pull request (instructions [here](https://github.com/awsdocs/amazon-ecr-user-guide/blob/master/CONTRIBUTING.md)) or send me a note via the Comments below. If your suggestion is likely to help others, I'll add it to the list of example lifecycle policies [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/lifecycle_policy_examples.html) in the Amazon ECR User Guide.

Thank you for your time. I look forward to hearing from you!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
