### ISSUE TITLE
Amazon ECS tasks for Windows (platform 1.0.0) require both ecr.dkr and ecr.api VPC endpoints

### ISSUE THREAD

**Issue by mateusmuller** [awsdocs/amazon-ecr-user-guide#55]
https://docs.aws.amazon.com/AmazonECR/latest/userguide/vpc-endpoints.html#ecr-vpc-endpoint-considerations

The above documentation states the following:

- Amazon ECS tasks hosted on Fargate using platform version 1.3.0 or earlier only require the com.amazonaws.region.ecr.dkr Amazon ECR VPC endpoint and the Amazon S3 gateway endpoint to take advantage of this feature.

Although, I believe this applies for Linux tasks only. Users can get confused with a Windows task hosted on Fargate (platform 1.0.0) since it's less than 1.3.0.

Can we improve the doc and states clearly this is for Linux only? Thank you!

**Comment by joelbrandenburg** [comment]
We've updated that documentation to reflect this.  We appreciate you bringing this to our attention!
